DATASET:
  path: ""
  LIST:
    train: "train_motion_pdiot-data.odgt"
    val: "val_motion_pdiot-data.odgt"
    test: "test_motion_pdiot-data.odgt"


MODEL:
  INPUT:
    sensor: "all"
    format: "normal"
    window_size: 25
  ARCH:
    type: "log"
  num_classes: 2


TRAIN:
  path: ""
  seed: -1
  DATA:
    overlap_size: 10
    batch_size: 64
  LEN:
    num_epoch: 100
    early_stop: 10
  OPTIM:
    optim: "sgd"
    lr: 0.001
    momentum: 0.9
    weight_decay: 0.0005
  LR:
    schedule: 'step'
    step_size: 40
    gamma: 0.1