DATASET:
  path: ""
  LIST:
    train: "train_dynamic_pdiot-data.odgt"
    val: "val_dynamic_pdiot-data.odgt"

MODEL:
  arch: "mlp"
  sensor: "all"
  input: "normal"

TRAIN:
  path: ""
  seed: -1
  DATA:
    batch_size: 32
    num_workers: 4
    disp_iter: 20
  LEN:
    num_epoch: 10
    start_epoch: 0
    early_stop: 2
  OPTIM:
    optim: "sgd"
    lr: 0.005
    momentum: 0.9
    weight_decay: 0.0005
  LR:
    schedule: 'step'
    step_size: 3
    gamma: 0.1
