DATASET:
  LIST:
    test: test_breath_pdiot-data.odgt
    train: train_breath_pdiot-data.odgt
    val: val_breath_pdiot-data.odgt
  num_classes: 4
  path: /disk/scratch/s1915791/git/pdiot-ml/data/sets/pdiot-data
MODEL:
  ARCH:
    LSTM:
      hidden_size: 128
      num_layers: 1
    MLP:
      dropout: 1.0
      hidden_size: 0
      num_layers: 0
  INPUT:
    format: window
    sensor: all
    window_size: 15
TRAIN:
  DATA:
    batch_size: 128
    overlap_size: 12
  FN:
    config: config.yaml
    history: history.csv
    log: log.txt
    weight: weights.hdf5
  LEN:
    early_stop: 10
    num_epoch: 100
  LR:
    gamma: 0.1
    schedule: step
    step_size: 40
  OPTIM:
    lr: 0.001
    momentum: 0.9
    optim: adam
    weight_decay: 0.0005
  path: /disk/scratch/s1915791/git/pdiot-ml/ckpt/breath-lstm