DATASET:
  num_classes: 4

MODEL:
  ARCH:
    CNN:
      depth_scaling: 0.5
      kernel_size: 7
      pool_size: 2
      dropout: 0.0
      hidden_size: 64
      num_layers: 2
    MLP:
      dropout: 0.5
      hidden_size: 100
      num_layers: 1
  INPUT:
    format: window
    sensor: all
    fft: True