DATASET:
  num_classes: 6
  LIST:
    train: train_dynamic_pdiot-data.odgt
    val: val_dynamic_pdiot-data.odgt

MODEL:
  ARCH:
    LSTM:
      hidden_size: 128
      num_layers: 1
    MLP:
      dropout: 1.0
      hidden_size: 0
      num_layers: 0
  INPUT:
    format: window
    sensor: accel
    window_size: 50

TRAIN:
  DATA:
    overlap_size: 0
    batch_size: 128
  LEN:
    num_epoch: 100
    early_stop: 10
  OPTIM:
    optim: adam
    lr: 0.001
    momentum: 0.9
    weight_decay: 0.0005
  LR:
    schedule: step
    step_size: 40
    gamma: 0.1
