DATASET:
  num_classes: 6

MODEL:
  ARCH:
    LSTM:
      hidden_size: 128
      num_layers: 1
    MLP:
      dropout: 1.0
      hidden_size: 0
      num_layers: 0
  INPUT:
    format: window
    sensor: accel

TRAIN:
  LEN:
    num_epoch: 20
  OPTIM:
    optim: adam
    lr: 0.001
    momentum: 0.9
    weight_decay: 0.0005