DATASET:
  path: ""
  num_classes: 2
  LIST:
    train: "train_motion_pdiot-data.odgt"
    val: "val_motion_pdiot-data.odgt"
    test: "test_motion_pdiot-data.odgt"

MODEL:
  INPUT:
    sensor: "all"
    format: "window"
    window_size: 15
  ARCH:
    LSTM:
      num_layers: 1
      hidden_size: 16
    MLP:
      num_layers: 0

TRAIN:
  path: ""
  DATA:
    overlap_size: 5
    batch_size: 128
  LEN:
    num_epoch: 100
    early_stop: 10
  OPTIM:
    optim: "adam"
    lr: 0.001
    momentum: 0.9
    weight_decay: 0.0005
  LR:
    schedule: 'step'
    step_size: 40
    gamma: 0.1
