DATASET:
  num_classes: 3

MODEL:
  ARCH:
    CNN:
      kernel_size: 3
      pool_size: 2
      dropout: 0.0
      hidden_size: 32
      num_layers: 2
    MLP:
      dropout: 0.5
      hidden_size: 100
      num_layers: 1
  INPUT:
    format: window
    sensor: accel