DATASET:
  component: breath
  odgt: full_t3_pdiot-data.odgt
  path: /disk/scratch/s1915791/git/imu-har/data/sets/pdiot-data
  task: 3
MODEL:
  ARCH:
    CNN:
      depth_scaling: 1.0
      dropout: 0.5
      hidden_size: 64
      kernel_size: 5
      num_layers: 2
      pool_size: 2
      residual: False
    LSTM:
      dropout: 0.5
      hidden_size: 64
      num_layers: 1
    MLP:
      dropout: 0.0
      hidden_size: 64
      num_layers: 1
  INPUT:
    fft: True
    format: window
    norm: False
    sensor: accel
    window_size: 50
  l2: 0.0
TRAIN:
  DATA:
    batch_size: 128
    overlap_size: 40
  FN:
    config: config.yaml
    history: history.csv
    log: log.txt
    weight: weights.hdf5
  LEN:
    early_stop: 3
    num_epoch: 10
  LR:
    gamma: 0.1
    schedule: step
    step_size: 100
  OPTIM:
    lr: 0.001
    momentum: 0.9
    optim: adam
    weight_decay: 0.0005
  path: /disk/scratch/s1915791/git/imu-har/ckpt/train/task_3_breath